[graph]
targets = []

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "Unicode-3.0"
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
