/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function transform(code: string, options: string): TransformOutput

export interface TransformOutput {
  code: string
  map?: string
}
